{
  imports = [
    ./ai.nix
    ./audio.nix
    ./caddy.nix
    ./cloudflared.nix
    ./ddclient.nix
    ./gitea.nix
    ./grub.nix
    ./immich.nix
    ./memos.nix
    ./minecraft-server.nix
    ./network.nix
    ./nextcloud.nix
    ./nginx.nix
    ./plymouth.nix
    ./samba.nix
    ./stylix.nix
    ./syncthing-client.nix
    ./syncthing-server.nix
    ./tailscale.nix
    ./vaultwarden.nix
    ./virtualisation.nix
    ./pihole.nix
    ./pufferpanel.nix
    ./fcitx5.nix
  ];
}
